_wandb:
    value:
        cli_version: 0.23.1
        e:
            aqymof0grjx2kk8n5dw4mwqsb4eopexh:
                codePath: /home/user/github/junius/de-LLM/ipynbs/tools/wandb.ipynb
                codePathLocal: wandb.ipynb
                email: junius.zhou@gmail.com
                executable: /home/user/github/junius/de-LLM/.venv/bin/python
                git:
                    commit: 1faa73883ce1ae57025f2919fb54ee1ab672fc5a
                    remote: https://juniuszhou:@github.com/juniuszhou/de-LLM
                host: user-X870-EAGLE-WIFI7
                os: Linux-6.14.0-37-generic-x86_64-with-glibc2.39
                program: /home/user/github/junius/de-LLM/ipynbs/tools/wandb.ipynb
                python: CPython 3.12.3
                root: /home/user/github/junius/de-LLM/ipynbs/tools
                startedAt: "2026-01-09T12:09:02.538582Z"
                writerId: aqymof0grjx2kk8n5dw4mwqsb4eopexh
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 105
            "2":
                - 1
                - 105
            "3":
                - 2
                - 13
                - 15
                - 16
            "4": 3.12.3
            "5": 0.23.1
            "8":
                - 1
            "12": 0.23.1
            "13": linux-x86_64
batch_size:
    value: 32
epochs:
    value: 10
learning_rate:
    value: 0.001
model:
    value: simple-nn
